/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as SearchRouteImport } from './routes/search';
import { Route as ProfileRouteImport } from './routes/profile';
import { Route as LoginRouteImport } from './routes/login';
import { Route as CartRouteImport } from './routes/cart';
import { Route as IndexRouteImport } from './routes/index';
import { Route as OrdersIndexRouteImport } from './routes/orders/index';
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId';
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId';
import { Route as CategoriesCategoryRouteImport } from './routes/categories/$category';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any);
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any);
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/cart': typeof CartRoute;
  '/login': typeof LoginRoute;
  '/profile': typeof ProfileRoute;
  '/search': typeof SearchRoute;
  '/signup': typeof SignupRoute;
  '/categories/$category': typeof CategoriesCategoryRoute;
  '/orders/$orderId': typeof OrdersOrderIdRoute;
  '/products/$productId': typeof ProductsProductIdRoute;
  '/orders/': typeof OrdersIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/cart': typeof CartRoute;
  '/login': typeof LoginRoute;
  '/profile': typeof ProfileRoute;
  '/search': typeof SearchRoute;
  '/signup': typeof SignupRoute;
  '/categories/$category': typeof CategoriesCategoryRoute;
  '/orders/$orderId': typeof OrdersOrderIdRoute;
  '/products/$productId': typeof ProductsProductIdRoute;
  '/orders': typeof OrdersIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/cart': typeof CartRoute;
  '/login': typeof LoginRoute;
  '/profile': typeof ProfileRoute;
  '/search': typeof SearchRoute;
  '/signup': typeof SignupRoute;
  '/categories/$category': typeof CategoriesCategoryRoute;
  '/orders/$orderId': typeof OrdersOrderIdRoute;
  '/products/$productId': typeof ProductsProductIdRoute;
  '/orders/': typeof OrdersIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/cart'
    | '/login'
    | '/profile'
    | '/search'
    | '/signup'
    | '/categories/$category'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/orders/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/cart'
    | '/login'
    | '/profile'
    | '/search'
    | '/signup'
    | '/categories/$category'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/orders';
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/login'
    | '/profile'
    | '/search'
    | '/signup'
    | '/categories/$category'
    | '/orders/$orderId'
    | '/products/$productId'
    | '/orders/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CartRoute: typeof CartRoute;
  LoginRoute: typeof LoginRoute;
  ProfileRoute: typeof ProfileRoute;
  SearchRoute: typeof SearchRoute;
  SignupRoute: typeof SignupRoute;
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute;
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute;
  ProductsProductIdRoute: typeof ProductsProductIdRoute;
  OrdersIndexRoute: typeof OrdersIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/search': {
      id: '/search';
      path: '/search';
      fullPath: '/search';
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/profile': {
      id: '/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/cart': {
      id: '/cart';
      path: '/cart';
      fullPath: '/cart';
      preLoaderRoute: typeof CartRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/orders/': {
      id: '/orders/';
      path: '/orders';
      fullPath: '/orders/';
      preLoaderRoute: typeof OrdersIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/products/$productId': {
      id: '/products/$productId';
      path: '/products/$productId';
      fullPath: '/products/$productId';
      preLoaderRoute: typeof ProductsProductIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/orders/$orderId': {
      id: '/orders/$orderId';
      path: '/orders/$orderId';
      fullPath: '/orders/$orderId';
      preLoaderRoute: typeof OrdersOrderIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/categories/$category': {
      id: '/categories/$category';
      path: '/categories/$category';
      fullPath: '/categories/$category';
      preLoaderRoute: typeof CategoriesCategoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
